#!/bin/bash
if [ $# -lt 1 ]; then
	echo "参数错了。"
	exit 1

else
	param=''
	params=()
	for arg in $@; do
		
		if [ $arg == '光盘' ]; then
			load_iso='-r -o loop'
			param=$load_iso
		else
			params+=("$arg")
		fi
	done
	merged_params=$(printf '%s ' "${params[@]}")
	merged_params="${merged_params%% }"
	mount $param $merged_params
fi
